"""Generate docs/eventtree-data.js for the designed animation, from the engine.

One frame per step of the slider: the initiating event alone, then the tree after each
barrier is added, then the settled end states. Every probability is computed, not written.

    PYTHONPATH=src python3 docs/gen_eventtree_data.py
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "src"))
sys.path.insert(0, os.path.join(HERE, "..", "..", "csakernel", "src"))

from csakernel import Ledger                       # noqa: E402
from pet.evidence import sequence_evidence          # noqa: E402
from pet.model import load_model                    # noqa: E402
from pet.quant import closure_error, end_state_frequencies   # noqa: E402
from pet.sequences import sequences                 # noqa: E402

EX = os.path.join(HERE, "..", "examples", "datacentre")


def partials(tree, upto):
    """Every path through the first `upto` barriers, with its running probability."""
    out = [("", 1.0)]
    for b in tree.barriers[:upto]:
        nxt = []
        for pattern, p in out:
            nxt.append((pattern + "S", p * (1.0 - b.failure_probability)))
            nxt.append((pattern + "F", p * b.failure_probability))
        out = nxt
    return out


def main() -> None:
    tree = load_model(os.path.join(EX, "model.json"))
    led = Ledger.load(os.path.join(EX, "ledger.json"))
    seqs = sequences(tree)
    f0 = tree.initiator.frequency

    barriers = [{
        "id": b.id, "label": tree.label(b), "name": b.name,
        "fails": b.failure_probability, "works": 1.0 - b.failure_probability,
        "evidence_class": led.evidence_class(b.ledger_ref),
        "origin": led.origin(b.ledger_ref),
        "authored_by": b.authored_by,
    } for b in tree.barriers]

    frames = [{
        "step": 0, "title": "The initiating event",
        "text": f"{tree.label(tree.initiator)}, {f0:.3g} per period. Everything that follows "
                "is conditional on this.",
        "paths": [{"pattern": "", "conditional": 1.0, "frequency": f0}],
    }]
    for k, b in enumerate(tree.barriers, start=1):
        rows = [{"pattern": pat, "conditional": p, "frequency": p * f0}
                for pat, p in partials(tree, k)]
        frames.append({
            "step": k, "title": f"Barrier {k}: {b.name}",
            "text": f"It fails on demand with probability {b.failure_probability:.3g}, so each "
                    f"path splits: {1 - b.failure_probability:.3g} that it holds, "
                    f"{b.failure_probability:.3g} that it does not.",
            "barrier": b.id, "paths": rows,
        })
    frames.append({
        "step": len(tree.barriers) + 1, "title": "The end states",
        "text": "Each path lands on an outcome; paths that land on the same outcome add up.",
        "paths": [{
            "pattern": s.pattern, "id": s.id, "conditional": s.conditional,
            "frequency": s.frequency, "end_state": s.end_state,
            "failed": [tree.label(b) for b in tree.barriers if b.id in s.failed],
            "evidence_class": sequence_evidence(tree, led, s),
        } for s in seqs],
        "end_states": [{"state": st, "frequency": fr,
                        "severity": tree.severity.get(st, 0)}
                       for st, fr in end_state_frequencies(tree, seqs).items()],
    })

    data = {
        "initiator": {"id": tree.initiator.id, "label": tree.label(tree.initiator),
                      "name": tree.initiator.name, "frequency": f0,
                      "evidence_class": led.evidence_class(tree.initiator.ledger_ref),
                      "origin": led.origin(tree.initiator.ledger_ref)},
        "barriers": barriers,
        "steps": ["The initiating event"] + [f"Barrier {i}: {b.short or b.name}"
                                             for i, b in enumerate(tree.barriers, 1)]
                 + ["The end states"],
        "frames": frames,
        "closure": 1.0 + closure_error(tree, seqs),
        "credit": "Rasmussen, WASH-1400 (1975); Vesely, Goldberg, Roberts & Haasl, "
                  "Fault Tree Handbook (NUREG-0492, 1981), ch. III",
    }

    out = os.path.join(HERE, "eventtree-data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by docs/gen_eventtree_data.py - do not edit by hand.\n")
        fh.write("// Probabilities come from examples/datacentre via pet.sequences;\n")
        fh.write("// regenerate after any model change.\n")
        fh.write("window.EVENTTREE = ")
        json.dump(data, fh, ensure_ascii=False, indent=2)
        fh.write(";\n")
    print(f"wrote {out} ({os.path.getsize(out)} bytes, {len(frames)} frames)")


if __name__ == "__main__":
    main()
